### ISSUE TITLE
two right sidebars - they are stacked

### ISSUE THREAD

**Issue by porwig** [bamboothemes/gazetta#10]
With Firefox 39 / Windows 7 - 22inch LCD @ full screen: 1440x900
two right sidebars - they are stacked

**Comment by porwig** [comment]
![2rightsidebars-01](https://cloud.githubusercontent.com/assets/2353742/9252822/b7618a6a-4197-11e5-9f53-daed75fb8da7.jpg)

**Comment by locii** [comment]
Config issue thanks
