### ISSUE TITLE
left sidebar - theme changes and logo row changes

### ISSUE THREAD

**Issue by porwig** [bamboothemes/gazetta#11]
With Firefox 39 / Windows 7
left sidebar - changes theme colors & logo size, no search field

**Comment by porwig** [comment]
![leftsidebar-01](https://cloud.githubusercontent.com/assets/2353742/9252527/035c406a-4196-11e5-9328-4c78d8112b5a.jpg)

**Comment by locii** [comment]
Fixed thankyou!
