### ISSUE TITLE
two left sidebars - positioning off?

### ISSUE THREAD

**Issue by porwig** [bamboothemes/gazetta#12]
With Firefox 39 / Windows 7
two left sidebars - not sure if sidebars are displaying as intended

**Comment by porwig** [comment]
![2leftsidebars-01](https://cloud.githubusercontent.com/assets/2353742/9252510/ec7cf1d2-4195-11e5-9a07-54201aa358cc.jpg)

**Comment by locii** [comment]
Thanks Paul - Im not able to see that here with the latest version.
Was that at a specific browser width?

**Comment by porwig** [comment]
Hi Anthony - my browsers are/were set to full width, which is 1440 pixels on my desktop LCD.

I just re-checked in Mozilla 39 and Chrome 44, both on Windows 7, and at 1440 pixels wide. Now, for me, in both of those browsers, the two sidebars are stacking - see attached.
![2leftsidebars-02](https://cloud.githubusercontent.com/assets/2353742/9266037/06c2252c-41f9-11e5-8730-4be156f9b18b.jpg)

**Comment by locii** [comment]
Hmm thanks I dont see it here local or live. Ill update the theme now to see if you can still see it. Can you try now?

**Comment by porwig** [comment]
I just re-checked, they are still stacking for me, but the background is now more of an aqua instead of the green.

Feel free to close this if you can't reproduce it!

**Comment by locii** [comment]
Thanks Ill see if Rob can see it.

**Comment by porwig** [comment]
I just checked the production demo, and I do not see this issue any more.
