### ISSUE TITLE
color issues

### ISSUE THREAD

**Issue by woodsy751** [bamboothemes/gazetta#13]
http://bambootheme.com/showcase/aug15/template-features/layouts/right-sidebar

the module in the 

<div class="zt-image zt-rounded zt-flat-shadow fullwidth zt-hidden-content zt-block zt-element zt-element-1">
                    <a href="/showcase/aug15/component/contact/contact/2">
            
                            
                        <img class="lazyOwl" src="http://bambootheme.com/showcase/aug15/media/mod_zentools2/cache/images/unsplash_52a9920595941_1-b9e2f9ae9eb1bcd8ce2d6af57b32feec.jpg" alt="Speci De Fineas">
                            
                    </a>
            </div>

![bamboo](https://cloud.githubusercontent.com/assets/517125/9261951/c4240cc4-4254-11e5-86b3-64b19f4de666.png)

**Comment by locii** [comment]
Fixed
