### ISSUE TITLE
category blog 1 column - 1 pixel line in offcanvas

### ISSUE THREAD

**Issue by porwig** [bamboothemes/gazetta#8]
With Firefox 39 / Windows 7
category blog 1 column - open offcanvas: see white 1 pixel horizontal white line across offcanvas

**Comment by porwig** [comment]
![catblog1col-01](https://cloud.githubusercontent.com/assets/2353742/9252549/27635994-4196-11e5-9da2-464836f22bdc.jpg)

**Comment by locii** [comment]
Nice spot - fixed thanks
