### ISSUE TITLE
single article - main content above header image

### ISSUE THREAD

**Issue by porwig** [bamboothemes/gazetta#9]
With Firefox 39 / Windows 7
single article - top of main content seems misaligned (covers header image)

**Comment by porwig** [comment]
![article-01](https://cloud.githubusercontent.com/assets/2353742/9252537/1936fd4e-4196-11e5-9083-65563f65e418.jpg)

**Comment by locii** [comment]
Ah yes thats by design. There is a setting in the template that allows you to control the top offset of the sidebar if you want to have it evened up.
